---
# <ansible_base_dir>/group_vars/kubernetes.yaml
#
ansible_user: ubuntu
vars:
      packages_to_remove:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      packages_to_install:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      docker_packages:
        - docker-ce     
        - docker-ce-cli
        - containerd.io
